# 提供生成所有ID服务

# 自定义变量
snowflake:
  workerId: 1
  dataCenterId: 1

spring:
  application:
    name: snowflake-service
  redis: # redis配置 ========================
    host: localhost
    port: 6379
    timeout: 5000ms
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848

server:
  port: 8751

management:
  endpoints:
    web:
      exposure:
        include: "*"

logging:
  file: var/log/snowflake-service.log
  level:
    com:
      todo:
        system:
          service: DEBUG
