server:
  port: 8060

spring:
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
  application:
    name: all-service

management:
  endpoints:
    web:
      exposure:
        include: '*'



