server:
  port: 8050

spring:
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
    config:
      server:
        git:
          uri: 'file://${user.dir}/src/main/resources/config'
  application:
    name: config-server

management:
  endpoints:
    web:
      exposure:
        include: '*'



