server:
  port: 8070

spring:
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
  application:
    name: app-backend

management:
  endpoints:
    web:
      exposure:
        include: '*'



